### ISSUE TITLE
Add mappings to TO

### ISSUE THREAD

**Issue by cmungall** [Planteome/ibp-cassava-traits#3]
See checklist: https://github.com/Planteome/plant-trait-ontology/issues/374

Currently there are neither xrefs in the .obo nor a column in the TD5 xls

**Comment by cmungall** [comment]
Should I do an automatic mapping?

**Comment by marieALaporte** [comment]
@cmungall I have done the mappings in a google spreadsheet. 
Then, I added them in the obo file. As we are still reviewing the mappings, I did not push it.

**Comment by cmungall** [comment]
I'll add the obo on a branch
