### ISSUE TITLE
Softness of boiled cassava roots

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/ibp-cassava-traits#33]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Paula Iragaba    |
| **Program** | National Crops Resources Research Institute (NaCRRI) |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Softness of boiled cassava roots    |
| **Definition**         | Mechanical attribute of boiled cassava roots relating to force required to make them compressed     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Use of a penetrometer to record the maximum force used to penetrate the boiled root        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | Newton           |

**Comment by nmenda** [comment]
https://github.com/Planteome/ibp-cassava-traits/blob/a638aa2df2ff1a23f2f1d77bb22c88842307dfda/cassava_trait.obo#L5794
