### ISSUE TITLE
Rust disease incidence 

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/ibp-cassava-traits#41]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Luciano Rogerio Braatz de Andrade    |
| **Program** | EMBRAPA |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Rust disease incidence 6-month evaluation    |
| **Definition**         | Proportion of plants within a plot showing symptoms of Rust, evaluated close to six months after planting.     |
| **Trait Class**        |    |
| **Measurement Method** | Proportion of plants within a plot showing symptoms of Rust        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | %           |

**Comment by bauchetg** [comment]
trait evaluated at 6 and 9 months, i closed the redundant issue

**Comment by bauchetg** [comment]
replaced by #47
