### ISSUE TITLE
Rust disease incidence 9-month evaluation

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/ibp-cassava-traits#42]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Luciano Rogerio Braatz de Andrade    |
| **Program** | EMBRAPA |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Rust disease incidence 9-month evaluation    |
| **Definition**         | Proportion of plants within a plot showing symptoms of Rust, evaluated close to nine months after planting.
     |
| **Trait Class**        | Biotic Stress   |
| **Measurement Method** | Proportion of plants within a plot showing symptoms of Rust        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | %           |

**Comment by bauchetg** [comment]
redundant of #41
