### ISSUE TITLE
change TO mapping to xrefs?

### ISSUE THREAD

**Issue by nmenda** [Planteome/ibp-cassava-traits#6]
can we update the TO mappings from is_a relationship to xrefs? 
e.g. 
https://github.com/Planteome/ibp-cassava-traits/blob/master/cassava-trait-ontology.obo#L84

**Comment by marieALaporte** [comment]
we added this TO term in order to test the display of the mapping in our browser. You can remove it or use xref

**Comment by nmenda** [comment]
https://github.com/Planteome/ibp-cassava-traits/commit/d924c01076b6849766f3346ec08a09c1844ecb80
