### ISSUE TITLE
Add other term series for post composed trait

### ISSUE THREAD

**Issue by aafolabi** [Planteome/ibp-cassava-traits#76]
Add term series for phenotyping done in tiers.

Root section 
- Proximal
- Axial
- Distal

Stem portion
- Hardwood (lower woody stem portion)
- Semi-hardwood (mid part)
- Green shoot
- Tip shoot

Leaf area
Leaves can be collected from different parts of the stem
- Hardwood (lower woody stem portion)
- Semi-hardwood (mid part)
- Green shoot
- Tip shoot

Treatment type
- Raw
- Boiled
- Fried
- Dried

**Comment by aafolabi** [comment]
Sample preparation method should be added as well.
Mashed, Grated

**Comment by nmenda** [comment]
https://github.com/solgenomics/sgn/commit/5aaceaba20f1ddfe24a5d06ebfc2763ea0902d1e
