### ISSUE TITLE
Bemesia tabaci typo

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/ibp-cassava-traits#79]
Some biotic stress traits are named after Bemesia tabaci.
I think there is a typo and it should be Bemisia tabaci (https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?name=Bemisia+tabaci) 

@aafolabi could you check and make the change of this is a typo.

**Comment by nmenda** [comment]
https://github.com/Planteome/ibp-cassava-traits/commit/9758979ced1ea03ba723ef728c017d7468bf1746

**Comment by nmenda** [comment]
https://github.com/Planteome/ibp-cassava-traits/commit/a934aa31f8f85cd70b47013ef69f6cf884cc6f7a
