### ISSUE TITLE
Create: Texture Max Force

### ISSUE THREAD

**Issue by Meghar5** [Planteome/ibp-cassava-traits#83]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Karima Meghar    |
| **Program** | Cirad |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Texture Max Force    |
| **Proposed Synonyms**  | TMF     |
| **Definition**         | Texture of boiled cassava     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Texture measurement        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | g          |

**Comment by marieALaporte** [comment]
Successful test! I close it for now
