### ISSUE TITLE
Textural characteristics of boiled roots in cassava

### ISSUE THREAD

**Issue by aafolabi** [Planteome/ibp-cassava-traits#88]
Texture   characteristic Gradient of boiled cassava roots
Texture characteristic Max.   Force of boiled cassava roots
Texture characteristic   Distance at Max. Force of boiled cassava roots
Texture characteristic End   force of boiled cassava roots
Texture characteristic Area   under Curve of boiled cassava roots
Texture characteristic Linear   Distance of boiled cassava roots

**Comment by nmenda** [comment]
https://github.com/Planteome/ibp-cassava-traits/pull/89/commits/19cc981e988fa9a9ecc752bb72e8c8b4be23afa3
